export const FETCH_PERSON_LIST_START = 'FETCH_PERSON_LIST_START';
export const FETCH_PERSON_LIST_FAIL = 'FETCH_PERSON_LIST_FAIL';
export const FETCH_PERSON_LIST_SUCCESS = 'FETCH_PERSON_LIST_SUCCESS';

export const FETCH_PERSON_INDIVIDUAL_START = 'FETCH_PERSON_INDIVIDUAL_START';
export const FETCH_PERSON_INDIVIDUAL_FAIL = 'FETCH_PERSON_INDIVIDUAL_FAIL';
export const FETCH_PERSON_INDIVIDUAL_SUCCESS = 'FETCH_PERSON_INDIVIDUAL_SUCCESS';

export const DELETE_PERSON_INDIVIDUAL_START = 'DELETE_PERSON_INDIVIDUAL_START';
export const DELETE_PERSON_INDIVIDUAL_FAIL = 'DELETE_PERSON_INDIVIDUAL_FAIL';
export const DELETE_PERSON_INDIVIDUAL_SUCCESS = 'DELETE_PERSON_INDIVIDUAL_SUCCESS';

export const CREATE_PERSON_INDIVIDUAL_START = 'CREATE_PERSON_INDIVIDUAL_START';
export const CREATE_PERSON_INDIVIDUAL_FAIL = 'CREATE_PERSON_INDIVIDUAL_FAIL';
export const CREATE_PERSON_INDIVIDUAL_SUCCESS = 'CREATE_PERSON_INDIVIDUAL_SUCCESS';


export const UPDATE_PERSON_INDIVIDUAL_START = 'UPDATE_PERSON_INDIVIDUAL_START';
export const UPDATE_PERSON_INDIVIDUAL_FAIL = 'UPDATE_PERSON_INDIVIDUAL_FAIL';
export const UPDATE_PERSON_INDIVIDUAL_SUCCESS = 'UDPATE_PERSON_INDIVIDUAL_SUCCESS';